### ISSUE TITLE
Solar roofing gives an error and is replaced with normal roofing

### ISSUE THREAD

**Issue by CrunchyDuck** [AaronCRobinson/ExpandedRoofing#13]
A comment was posted on the Steam upload of the mod, that said the following:

> I am not getting any error messages, but a high percentage, probably 80%+ of the solar roofing I build turns into Constructed Roof upon completion; it is called solar roofing (building), and then when completed, called constructed roof. Not sure what is happening there.

I got my partner to do a bit of testing, and he confirmed it happens only when:

1. Not connected to a solar controler or an already existing solar roof
2. Is built by a pawn, not build in God-mode.

He provided me with his output_log.txt, which I'll link to below. The errors are the last blocks from line 168 till the end.

https://gist.github.com/HugsLibRecordKeeper/fbdcec85e9d78d4b1dd4f7551174580e#file-output_log-txt-L22

**Comment by AaronCRobinson** [comment]
This is related to performance changing in SolarRoofing tracking. I had implemented a poor way of doing new keys for the tracker and if a "solar roofing set" was collapsed, there was the chance for a collision on the keys used in the dictionary. A new method of tracking a key was implemented and a new release (v0.19.2) is available.
