### ISSUE TITLE
Bug in SolarRoofingTracker

### ISSUE THREAD

**Issue by alexroeber** [AaronCRobinson/ExpandedRoofing#17]
I wondered why the solar roof area was always wrong, pretty sure it's this [line](https://github.com/AaronCRobinson/ExpandedRoofing/blob/master/Source/ExpandedRoofing/SolarRoofingTracker.cs#L97).
Shouldn't it be `found.ElementAt(i)` instead of `i`, just like the line before? Else you'd always delete the 2nd to xth cellset ever created, I think. Correct me if I'm wrong.

**Comment by AaronCRobinson** [comment]
Fixed in dc23c7bfb67e33c077ec2e8353fbdeff60684a45.

**Comment by AaronCRobinson** [comment]
I originally released the 1.0.0 but this will not get distributed then via Fluffy's mod manager. Therefore, I went ahead with a version bump to v1.0.1. Thanks for pointing this bug out.
