### ISSUE TITLE
[Bug]Ticking SolarController

### ISSUE THREAD

**Issue by cheesealmighty** [AaronCRobinson/ExpandedRoofing#18]
The devices work fine for a while, then go haywire, the following error is repeated for every controller.

https://paste.ubuntu.com/p/HTMxSKtF9N/

After replaced, they start working again, just to throw the same error again.

**Comment by AaronCRobinson** [comment]
Hey. I have an idea why this happened. I pushed a change from someone and I never tested it. However, I am busy for a bit, so I don't know when I will be able to fix this. I appreciate the bug report and will work on resolving this as I am more available.

**Comment by cheesealmighty** [comment]
Ah. No problem. Do let me know if I can help with some logs, but should be easily reproducible. As few other people reported it on the steam workshop.

**Comment by alexroeber** [comment]
Just some thought: My last issue was fixed but never ended up on steam, ever tried to use the [newest version](https://github.com/AaronCRobinson/ExpandedRoofing/releases)?

**Comment by AaronCRobinson** [comment]
There were still some issues that are fixed now in 1.0.2. I am closing out these issues. Also the "Caretaker" of the steam version is a different person. Handling all the community interaction ended up being too much of engagement for me. Thanks for bringing these bugs to my attention.
