### ISSUE TITLE
Controler not seeing all solar roof tiles

### ISSUE THREAD

**Issue by VexMex** [AaronCRobinson/ExpandedRoofing#19]
So i have this mod isntalled together with like 80 other mods, and all was working fine (sorta) till i had the mentioned error that others had already where the controller still works, but just shows an error in the data box in the bottom left

now at day 2 i found out that there arent all roof tiles being seen, the controller says 84 roof tiles even tho alst evening i was already at 96 (and even that i found a littlebit weird since its a "big" area. anyways i tried it again on another spot, there i suddenly had from 114 placed solar roofes only 69 that are seen and used. then i did the whole thing again on a different spot with a small roof, i placed 9 roof tiles and the controller, all ok, then i palce an additional 9, and the controler now was seeing 14. since i can actually do maths and it should be 18, i think there is another bug in the mod sadly.

anyways a great mod so thanks already for this

**Comment by alexroeber** [comment]
Wasn't that just fixed? #17

**Comment by VexMex** [comment]
well seems not like it sadly, i removed the main roof once and put it abck up, but that only bumped a 19x7 area up to 105 tiles

**Comment by alexroeber** [comment]
Uhm, are you using the steam version? I just wrote it here #18 , but the steam version is not up to date!

**Comment by VexMex** [comment]
well yeah using the steam version for comforts sake xD
i will try the nonsteam version soon and see if it makes the roofes count properly!

**Comment by VexMex** [comment]
ok so i just tested it with the new version, it does, or seem to count now correctly the tiles, but i have again 2 of the controllers throwing error since they werent connected yet to the main roof. 

the main error you can see on your linked error #18 but at the "at verse...." things i have a slightly different output as you can see here https://i.imgur.com/kP87i8N.jpg

**Comment by AaronCRobinson** [comment]
There were still some issues that are fixed now in 1.0.2. I am closing out these issues. Also the "Caretaker" of the steam version is a different person. Handling all the community interaction ended up being too much of engagement for me. Thanks for bringing these bugs to my attention.

Also, there should be no inconsistent states from changing the mod version and having bad counts previously from the tracker. The tracker is not being saved and is recalculated currently each load. Cheers.
