### ISSUE TITLE
Deconstruction of Objects under solar roofing

### ISSUE THREAD

**Issue by beilber** [AaronCRobinson/ExpandedRoofing#2]
When you designate an area to build solar roofing the objects in that same space are deconstructed.  So far the only exception I have noted are floors, walls and power conduits.

Even the solar controller gets deconstructed.  You can place the objects again once the roofing constructed.

**Comment by beilber** [comment]
Just to add, this has only been since B18

**Comment by AaronCRobinson** [comment]
This should be fixed in one of the last commits (c61ddbf). I will leave open for a few days just to confirm that it is resolved.

**Comment by AaronCRobinson** [comment]
Fixed.
