### ISSUE TITLE
To add Spanish translation

### ISSUE THREAD

**Issue by CANALETA** [AaronCRobinson/ExpandedRoofing#20]
Hey Aaron, I translated your mod to spanish (Castilian and Latin America), but cannot upload it here.
It says: "Uploads are disabled: file uploads require push access to this repository"
I'm not very skilled with github, sorry, but could you help me with this?

**Comment by AaronCRobinson** [comment]
You can mail it to me at robinson.aaron.c@gmail.com. I appreciate you translating the mod and can incorporate it that way. The way you would normally do it on github is via a "pull request". This is done by "cloning" the repository, making the changes in your clone, commit those changes, and then coming back to my repository and doing a "pull request" (which is telling me you have changes you want me to take from your copy of my work). This way we can all contribute to the work in an effective/open fashion. Feel free to e-mail me the changes and I can incorporate them that way too. Gracias.

**Comment by AaronCRobinson** [comment]
I have included this in 1.0.2. I love the little icons and will need to poke my other translators to start doing that. Thank you so much for doing this!
